import './globals.css';
import { Inter, Tajawal } from 'next/font/google';
import ModelProvider from '@/context/modelProvider';
const inter = Inter({ subsets: ['latin'] });
const tajawal = Tajawal({
  subsets: ['arabic', 'latin'],
  weight: ['400', '500', '700'],
  variable: '--font-tajawal',
});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${tajawal.className}`}>
        <ModelProvider>{children}</ModelProvider>
      </body>
    </html>
  );
}
